работа с селениумом
TsakunovR/AT2-Evgeniy pull request #2
Opened 2023-11-19 07:48 UTC by EvFrolov

2023-11-27 16:04 UTC, TsakunovR requested changes

2023-11-27 16:04 UTC, TsakunovR commented on pages/LoginPage.py
> +        self.find_element(LoginPageLocators.LOGIN_BUTTON)
Добавить проверки наличия остальных элементов

2023-11-27 17:25 UTC, EvFrolov commented on pages/LoginPage.py
> +        self.find_element(LoginPageLocators.LOGIN_BUTTON)
Добавил коммит с проверками

2023-11-27 17:41 UTC, TsakunovR approved these changes

2023-12-08 05:59 UTC, EvFrolov commented
забыл смёржить после аппрува
Добавил 2 коммита с домашними заданиями с 2х прошлых уроков

2023-12-11 15:29 UTC, TsakunovR approved these changes

2023-12-11 15:29 UTC, merged